# Generated by Django 5.2.4 on 2025-07-24 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route_planner', '0002_trip_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_data',
            field=models.JSONField(blank=True, help_text='Stores the calculated route data', null=True),
        ),
    ]
